::##############################################################################
:::
::: Batch Audio Converter
::: Generated by DeepSeek
:::
::: Description:
::: This script converts audio files between common formats using FFmpeg with
::: high-quality presets. It preserves metadata and creates organized output.
:::
::: Features:
::: - Supports input formats: mp3, wav, flac, aac, m4a, ogg, opus, wma, aiff,
:::   ape, alac, mka, webm
::: - Output formats: MP3, AAC, FLAC, WAV, OGG
::: - Quality presets:
:::   * MP3: 320 kbps CBR, 44.1kHz, stereo (LAME encoder)
:::   * AAC: 256 kbps VBR, 44.1kHz, stereo (FDK-AAC compatible)
:::   * FLAC: 16-bit, 44.1kHz, maximum compression
:::   * WAV: 16-bit PCM, 44.1kHz, uncompressed
:::   * OGG: 192 kbps VBR, 44.1kHz, stereo (Vorbis encoder)
:::   * WAV for Whisper: 15KHz, mono, uncompressed
::: - Automatic output folder creation
::: - Progress reporting and error handling
:::
::: Usage:
::: 1. Ensure FFmpeg is installed and in system PATH
::: 2. Double-click script or run from command prompt
::: 3. Follow on-screen prompts
:::
::: Parameters:
::: - No command-line parameters needed - fully interactive
::: - Customize quality settings by modifying the "set params" sections
::: - Modify audio_extensions list to add/remove supported input formats
:::
::: Example Use:
::: 1. Select output format: 3 (FLAC)
::: 2. Drag-and-drop input folder when prompted
::: 3. Find converted files in "[original folder]\converted_to_flac"
:::
::: Notes:
::: - Will overwrite existing files in output folder
::: - Conversion time depends on file sizes and system performance
:::
:::
::##############################################################################

@echo off
setlocal enabledelayedexpansion

:: Check if FFmpeg is available
where ffmpeg >nul 2>&1
if %errorlevel% neq 0 (
    echo FFmpeg is not found in your PATH.
    echo Please install FFmpeg and add it to your system PATH.
    pause
    exit /b
)

:: Display available formats
echo.
echo Supported output formats:
echo 1. MP3 (320 kbps, 44.1kHz, stereo)
echo 2. AAC (256 kbps, 44.1kHz, stereo)
echo 3. FLAC (16-bit, 44.1kHz, lossless)
echo 4. WAV (16-bit, 44.1kHz, uncompressed)
echo 5. OGG (192 kbps, 44.1kHz, stereo)
echo 6. WAV for Whisper (16-bit, 16000Hz, mono)
echo.

:: Get user input for output format
set /p "choice=Select output format (1-6): "
if "!choice!"=="1" (
    set extension=mp3
    set codec=libmp3lame
    set params=-b:a 320k -ar 44100 -ac 2
) else if "!choice!"=="2" (
    set extension=aac
    set codec=aac
    set params=-b:a 256k -ar 44100 -ac 2
) else if "!choice!"=="3" (
    set extension=flac
    set codec=flac
    set params=-compression_level 12 -ar 44100 -ac 2 -sample_fmt s16
) else if "!choice!"=="4" (
    set extension=wav
    set codec=pcm_s16le
    set params=-ar 44100 -ac 2
) else if "!choice!"=="5" (
    set extension=ogg
    set codec=libvorbis
    set params=-b:a 192k -ar 44100 -ac 2
) else if "!choice!"=="6" (
    set extension=wav
    set codec=pcm_s16le
    set params=-ar 15000 -ac 1
) else (
    echo Invalid selection.
    pause
    exit /b
)

:: Get input folder
set /p "input_folder=Enter input folder path (or drag folder here): "
if not exist "!input_folder!\" (
    echo Folder does not exist.
    pause
    exit /b
)

:: Create output folder
set output_folder=!input_folder!\converted_to_!extension!
if not exist "!output_folder!" mkdir "!output_folder!"

echo.
echo Starting conversion...
echo.

:: Define supported input extensions
set "audio_extensions=mp3 wav flac aac m4a ogg opus wma aiff ape alac mka webm"

:: Build the FOR loop pattern
set "file_pattern="
for %%e in (%audio_extensions%) do set "file_pattern=!file_pattern! "!input_folder!\*.%%e""

set count=0
for %%f in (%file_pattern%) do (
    ffmpeg -hide_banner -loglevel error -stats -i "%%f" -c:a !codec! !params! -map_metadata 0 -id3v2_version 3 -y "!output_folder!\%%~nf.!extension!"
    if !errorlevel! equ 0 (
        set /a count+=1
        echo Converted: %%~nxf to %%~nf.!extension!
    ) else (
        echo Failed to convert: %%~nxf
    )
)

echo.
echo Conversion complete.
echo Converted !count! files.
echo Output folder: !output_folder!
pause