:: ===========================================================================
:: Audio Extraction Batch Script
:: Generated by DeepSeek
::
:: Purpose: Extracts audio streams from video files using FFmpeg, attempting to
::          copy streams without re-encoding when possible.
::
:: Behavior:
::   1. File Processing:
::      - Recursively processes all supported video files in current directory
::        and subdirectories (MP4, MKV, AVI, MOV, FLV, WMV, WEBM, MPG, MPEG)
::      - Creates output files in specified directory (default: Extracted_Audio)
::
::   2. Audio Extraction Logic:
::      - First attempts direct stream copy (-c:a copy) for maximum quality
::      - Falls back to re-encoding if direct copy fails
::      - Uses specified codec (default: AAC) for re-encoded files
::
::   3. Exception Handling:
::      - Duplicate Files:
::        - Skips processing if output file already exists
::        - No overwriting by default (safe for multiple runs)
::
::      - FFmpeg Errors:
::        - Verifies FFmpeg is accessible before processing
::        - Handles cases where direct stream copy fails
::        - Provides clear error messages if FFmpeg fails completely
::
::      - Output Directory:
::        - Creates output directory if it doesn't exist
::
::   4. Argument Processing:
::      - Supports DOS-style arguments with / prefix
::      - Falls back to sensible defaults for all parameters
::      - Validates FFmpeg path before processing
::
:: Usage Examples:
::   Basic:               extract_audio.bat
::   Custom FFmpeg:       extract_audio.bat /ffmpeg_path "C:\Tools\ffmpeg.exe"
::   MP3 Output:          extract_audio.bat /output_ext .mp3 /codec libmp3lame
::   High Quality:        extract_audio.bat /quality 1
::   Help:                extract_audio.bat /help
::
:: Exit Codes:
::   0 - Success
::   1 - FFmpeg not found/accessible
::   2 - Invalid parameters (with /help display)
::
:: Notes:
::   - For direct stream copy, output extension should match input codec
::   - Quality scale depends on codec (1-5 for AAC/MP3, 1=best)
:: ===========================================================================

@echo off
setlocal enabledelayedexpansion

:: Default configuration
set "default_ffmpeg=ffmpeg.exe"
set "output_extension=.m4a"
set "output_folder=Extracted_Audio"
set "audio_codec=aac"
set "quality=2"

:: Parse command line arguments
:parse_args
if "%~1" neq "" (
    if /i "%~1"=="/ffmpeg_path" (
        set "ffmpeg_path=%~2"
        shift /2
        goto :parse_args
    )
    if /i "%~1"=="/output_ext" (
        set "output_extension=%~2"
        shift /2
        goto :parse_args
    )
    if /i "%~1"=="/output_dir" (
        set "output_folder=%~2"
        shift /2
        goto :parse_args
    )
    if /i "%~1"=="/codec" (
        set "audio_codec=%~2"
        shift /2
        goto :parse_args
    )
    if /i "%~1"=="/quality" (
        set "quality=%~2"
        shift /2
        goto :parse_args
    )
    if /i "%~1"=="/help" (
        call :show_help
        exit /b 0
    )
    shift
    goto :parse_args
)

:: Check if ffmpeg is specified or in PATH
if not defined ffmpeg_path (
    where ffmpeg >nul 2>&1
    if errorlevel 1 (
        set "ffmpeg_path=%default_ffmpeg%"
        echo Using default FFmpeg path: !ffmpeg_path!
    ) else (
        set "ffmpeg_path=ffmpeg.exe"
    )
)

:: Verify FFmpeg is accessible
"%ffmpeg_path%" -version >nul 2>&1
if errorlevel 1 (
    echo Error: FFmpeg not found at "!ffmpeg_path!"
    echo Please specify the correct path using /ffmpeg_path
    call :show_help
    pause
    exit /b 1
)

:: Create output folder if it doesn't exist
if not exist "%output_folder%" mkdir "%output_folder%"

echo Configuration:
echo   FFmpeg path:    "!ffmpeg_path!"
echo   Output folder:  "!output_folder!"
echo   Output format:  "!output_extension!"
echo   Audio codec:    "!audio_codec!"
echo   Quality:        "!quality!"
echo.

:: Process all video files
for /r %%F in (*.mp4 *.mkv *.avi *.mov *.flv *.wmv *.webm *.mpg *.mpeg) do (
    set "input_file=%%F"
    set "output_file=%%~nF%output_extension%"
    set "output_path=%output_folder%\!output_file!"
    
    if not exist "!output_path!" (
        echo Extracting audio from "!input_file!"...
        
        "%ffmpeg_path%" -i "!input_file!" -vn -c:a copy -y "!output_path!" 2>nul
        
        if errorlevel 1 (
            echo Could not copy audio stream directly, re-encoding to !audio_codec!...
            "%ffmpeg_path%" -i "!input_file!" -vn -c:a !audio_codec! -q:a !quality! -y "!output_path!"
        )
        
        echo Finished: !output_path!
    ) else (
        echo Skipping "!input_file!" - output already exists
    )
)

echo.
echo Audio extraction complete!
pause
exit /b 0

:show_help
echo Usage: %~n0 [/ffmpeg_path path] [/output_dir dir] [/output_ext ext] [/codec codec] [/quality n]
echo.
echo Parameters:
echo   /ffmpeg_path  Path to FFmpeg executable (default: checks PATH then uses ffmpeg.exe)
echo   /output_dir   Output directory (default: ./Extracted_Audio)
echo   /output_ext   Output file extension (default: .m4a)
echo   /codec        Audio codec for re-encoding (default: aac)
echo   /quality      Quality setting (1-5, 1=best) (default: 2)
echo   /help         Show this help message
echo.
echo
echo
echo Examples:
echo   %~n0 /ffmpeg_path "C:\Tools\ffmpeg.exe" /output_dir AudioFiles
echo   %~n0 /output_ext .mp3 /codec libmp3lame /quality 1
goto :eof